      - name: Install Haxelib (Modo Rápido)
        run: |
          haxelib setup ~/haxelib
          # Usamos GIT para ser instantâneo e o GitHub não cancelar
          haxelib git lime https://github.com/mcagabe19/lime
          haxelib git openfl https://github.com/openfl/openfl
          haxelib git flixel https://github.com/HaxeFlixel/flixel
          haxelib install flixel-addons --always
          haxelib install flixel-ui --always
          haxelib install tjson --always
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools
          haxelib run lime setup
