name: Droid Build Force
on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Libs (Otimizado para Download)
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.0.1 --always
          haxelib install openfl 9.2.1 --always
          haxelib install flixel 5.2.2 --always
          haxelib install flixel-addons --always
          haxelib install flixel-ui --always
          haxelib install tjson --always
          haxelib install SScript --always
          haxelib git extension-androidtools https://github.com/Shadow-Droid-Team/extension-androidtools --always
          haxelib git androiddialogs https://github.com/Shadow-Droid-Team/androiddialogs --always
          haxelib git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd --always
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit --always
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib run lime setup android

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build APK
        run: haxelib run lime build android -debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: DroidEngine-APK
          path: export/debug/android/bin/app/build/outputs/apk/debug/*.apk
