name: Droid Build Force 0.7.1h
on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install Libs (Diret√≥rios 2025)
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.1.1 --always
          haxelib install openfl 9.3.3 --always
          haxelib install flixel 5.5.0 --always
          haxelib install flixel-addons --always
          haxelib install flixel-ui --always
          haxelib install tjson --always
          haxelib install SScript --always
          haxelib install hxvlc --always
          
          # Links corrigidos para 2025
          haxelib git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd --always
          haxelib git extension-androidtools https://github.com/Shadow-Droid-Team/extension-androidtools --always
          haxelib git androiddialogs https://github.com/Shadow-Droid-Team/androiddialogs --always
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit --always
          
          haxelib run lime setup flixel
          haxelib run lime setup android
          haxelib run lime setup

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK (Debug/Release)
        run: haxelib run lime build android -debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DroidEngine-Debug
          path: export/debug/android/bin/app/build/outputs/apk/debug/*.apk
          
