      - name: Install Libs (Método Definitivo Haxelib)
        run: |
          haxelib setup ~/haxelib
          
          # Usando links oficiais que não mudam
          haxelib git lime https://github.com/openfl/lime --always
          haxelib git openfl https://github.com/openfl/openfl --always
          haxelib git flixel https://github.com/HaxeFlixel/flixel --always
          
          # Instalando versões estáveis direto do servidor Haxelib (Sem GitHub 404)
          haxelib install flixel-addons 3.2.1 --always
          haxelib install flixel-ui --always
          haxelib install tjson --always
          haxelib install SScript 21.0.1 --always
          haxelib install hxvlc --always
          
          # Se os links do Jigsaw caíram, usamos o substituto universal
          haxelib git extension-androidtools https://github.com/haxetools/extension-androidtools --always
          haxelib git androiddialogs https://github.com/haxetools/androiddialogs --always
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec --always
          
          haxelib run lime setup android
          haxelib run lime setup
