      - name: Install Libs (Otimizado 2025)
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.1.1 --always
          haxelib install openfl 9.3.3 --always
          haxelib install flixel 5.5.0 --always
          haxelib install flixel-addons --always
          haxelib install flixel-ui --always
          haxelib install tjson --always
          haxelib install SScript --always
          haxelib install hxvlc --always
          
          # SUBSTITUÍDOS OS LINKS MORTOS (Testados agora):
          # O hxCodec do Jigsaw caiu, usando o da SPLCoding:
          haxelib git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd --always
          
          # Usando Shadow-Droid-Team para o resto (Mais estável):
          haxelib git extension-androidtools https://github.com/Shadow-Droid-Team/extension-androidtools --always
          haxelib git androiddialogs https://github.com/Shadow-Droid-Team/androiddialogs --always
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit --always
          
          haxelib run lime setup flixel
          haxelib run lime setup android
          haxelib run lime setup
          
