      - name: Instalar Bibliotecas
        run: |
          haxelib setup ~/haxelib
          
          # 1. INSTALAR DEPENDÊNCIAS BÁSICAS DO HAXE (Obrigatório)
          haxelib install format --always --quiet
          haxelib install hxp --always --quiet
          haxelib install lime --always --quiet
          haxelib install openfl --always --quiet
          
          # 2. INSTALAR DEPENDÊNCIAS DO FLIXEL (Usadas pela Droid Engine)
          haxelib install flixel 5.2.2 --always --quiet
          haxelib install flixel-addons --always --quiet
          haxelib install flixel-ui --always --quiet
          haxelib install hscript --always --quiet
          haxelib install tjson --always --quiet
          haxelib install SScript --always --quiet
          haxelib install hxvlc --always --quiet
          
          # 3. OS SEUS 3 LINKS DE CONFIANÇA (Agora com as bases prontas)
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec --always
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit --always
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools --always
          
          # 4. REBUILD E FINALIZAÇÃO
          haxelib run lime rebuild tools --always
          
