name: Build Android Port
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5 # Versão mais estável para ports

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Install Android Components
        run: |
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-33" "build-tools;33.0.0" "ndk;21.4.7075529"
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV

      - name: Install Libs (O substituto do unish-lib.sh)
        run: |
          haxelib setup ~/haxelib
          # Baixando tudo direto para não depender de scripts externos
          git clone https://github.com/mcagabe19/lime --depth 1
          git clone https://github.com/openfl/openfl --depth 1
          git clone https://github.com/HaxeFlixel/flixel --depth 1
          git clone https://github.com/nebulatv/linc_luajit --depth 1
          git clone https://github.com/SPLCoding/hxCodec-but-it-works-xd --depth 1
          
          haxelib dev lime lime
          haxelib dev openfl openfl
          haxelib dev flixel flixel
          haxelib dev linc_luajit linc_luajit
          haxelib dev hxCodec hxCodec-but-it-works-xd
          
          haxelib install flixel-addons --always
          haxelib install flixel-ui --always
          haxelib install tjson --always
          haxelib install SScript --always
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools
          haxelib run lime setup android

      - name: Compile APK
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime build android -release

      - name: Publish APK
        uses: actions/upload-artifact@v4
        with:
          name: Port-Android-Final
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
