      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 7.9.0
          haxelib install openfl
          haxelib --never install flixel 5.2.2
          haxelib run lime setup flixel
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui
          haxelib install flixel-addons 3.0.2
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install SScript
          
          # Links de Preservação (Online em Dezembro de 2025)
          haxelib git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd.git --always
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit --always
          haxelib git extension-androidtools https://github.com/Shadow-Droid-Team/extension-androidtools --always
          haxelib git androiddialogs https://github.com/Shadow-Droid-Team/androiddialogs --always
          haxelib git devicelanguage https://github.com/Shadow-Droid-Team/devicelanguage --always
          
          haxelib install hxcpp-debug-server
          haxelib list
          
