          # ... (mantenha o início igual até o Install Libs)
          
      - name: Install Libs
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.1.1 --always
          haxelib install openfl 9.3.3 --always
          haxelib install flixel 5.5.0 --always
          haxelib install flixel-addons --always
          haxelib install flixel-ui --always
          haxelib install hscript --always
          haxelib install hxvlc --always
          haxelib install SScript --always
          haxelib install tjson --always
          # BIBLIOTECA DE IDIOMA QUE FALTOU:
          haxelib git extension-devicelang https://github.com/Tandest/extension-devicelang --always
          
          # SEUS 3 LINKS OK:
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec --always
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit --always
          haxelib git extension-androidtools https://github.com/LimeExtensions/extension-androidtools --always
          
      - name: Limpeza de Código (Remover Erros)
        run: |
          # 1. Remove androiddialogs do Project.xml
          sed -i '/androiddialogs/d' Project.xml
          
          # 2. Comenta a linha do DeviceLanguage que deu erro no import.hx
          sed -i 's/import extension.devicelang.DeviceLanguage;/\/\/import extension.devicelang.DeviceLanguage;/g' source/import.hx
          
          # 3. Limpa o arquivo AndroidDialogsExtend.hx para ele não travar o build
          echo "package backend;" > source/backend/AndroidDialogsExtend.hx
          echo "class AndroidDialogsExtend { public static function open(title:String, msg:String) {} }" >> source/backend/AndroidDialogsExtend.hx

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      # ... (continue com o restante do script igual ao anterior)
      
