name: Droid_Engine_Build_2025
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Instalar Libs
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.1.1 --always
          haxelib install openfl 9.3.3 --always
          haxelib install flixel 5.5.0 --always
          haxelib install flixel-addons --always
          haxelib install flixel-ui --always
          haxelib install hscript --always
          haxelib install tjson --always
          haxelib install SScript --always
          haxelib install hxvlc --always
          
          # =======================================================
          # AQUI ESTÃO OS 3 LINKS QUE VOCÊ VALIDOU (hxCodec, Lua e AndroidTools)
          # =======================================================
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec --always
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit --always
          haxelib git extension-androidtools https://github.com/LimeExtensions/extension-androidtools --always

      - name: Limpeza de Erros
        run: |
          # Remove o link morto do Project.xml para não dar erro 404
          sed -i '/androiddialogs/d' Project.xml || true
          
          # Cria o arquivo que falta para o jogo não travar sem o dialogs
          mkdir -p source/backend
          echo "package backend; class AndroidDialogsExtend { public static function open(t:String, m:String) {} }" > source/backend/AndroidDialogsExtend.hx

      - name: Setup Android
        uses: android-actions/setup-android@v3

      - name: Configurar Lime
        run: |
          # Isso diz ao Lime onde estão as ferramentas do Android
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_HOME/ndk-bundle
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime setup android -noprompt

      - name: Build APK
        run: |
          # Inicia a criação do APK oficial
          export ANDROID_SDK=$ANDROID_HOME
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
          haxelib run lime build android -debug

      - name: Upload (v4)
        uses: actions/upload-artifact@v4
        with:
          name: DroidEngine-Build
          path: export/debug/android/bin/app/build/outputs/apk/debug/*.apk
