name: Build Android Port
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Install Android Components
        run: |
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-33" "build-tools;33.0.0" "ndk;21.4.7075529"
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/21.4.7075529" >> $GITHUB_ENV

      - name: Install Libs (Sem erros de GIT)
        run: |
          haxelib setup ~/haxelib
          # Usando o comando nativo do haxelib para evitar erros de clone manual
          haxelib git lime https://github.com/mcagabe19/lime --always
          haxelib git openfl https://github.com/openfl/openfl --always
          haxelib git flixel https://github.com/HaxeFlixel/flixel --always
          haxelib git linc_luajit https://github.com/nebulatv/linc_luajit --always
          haxelib git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd --always
          
          # Instalando o resto
          haxelib install flixel-addons --always
          haxelib install flixel-ui --always
          haxelib install tjson --always
          haxelib install SScript --always
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools --always
          haxelib run lime setup android
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Lime
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME

      - name: Compile APK
        run: |
          haxelib run lime build android -release

      - name: Publish APK
        uses: actions/upload-artifact@v4
        with:
          name: Port-Android-Gerado
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
