name: Build Android Port
on:
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK/NDK
        uses: android-actions/setup-android@v3
      
      - name: Install Android Components
        run: |
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-33" "build-tools;33.0.0" "ndk;25.2.9519653"
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Install Libs (Links de SobrevivÃªncia)
        run: |
          haxelib setup ~/haxelib
          haxelib git lime https://github.com/openfl/lime --always
          haxelib git openfl https://github.com/openfl/openfl --always
          haxelib git flixel https://github.com/HaxeFlixel/flixel --always
          haxelib install flixel-addons 3.2.1 --always
          haxelib install flixel-ui --always
          haxelib install tjson --always
          haxelib install SScript 21.0.1 --always
          haxelib git hxCodec https://github.com/MAJigsaw77-Ports/hxCodec --always
          haxelib git extension-androidtools https://github.com/MAJigsaw77-Ports/extension-androidtools --always
          haxelib git androiddialogs https://github.com/MAJigsaw77-Ports/androiddialogs --always
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit --always
          haxelib run lime setup android
          haxelib run lime setup

      - name: Compile APK
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime build android -release
