      - name: Instalar Bibliotecas
        run: |
          haxelib setup ~/haxelib
          haxelib install format --always --quiet
          haxelib install hxp --always --quiet
          
          # LIME E OPENFL VIA GIT
          haxelib git lime https://github.com/openfl/lime --always
          haxelib git openfl https://github.com/openfl/openfl --always
          
          # SEUS 3 LINKS QUE FUNCIONAM
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec --always
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit --always
          haxelib git extension-androidtools https://github.com/LimeExtensions/extension-androidtools --always
          
          # DEMAIS DEPENDÃŠNCIAS (Sem a AndroidDialogs)
          haxelib install flixel 5.5.0 --always --quiet
          haxelib install flixel-addons --always --quiet
          haxelib install flixel-ui --always --quiet
          haxelib install hscript --always --quiet
          haxelib install tjson --always --quiet
          haxelib install SScript --always --quiet
          haxelib install hxvlc --always --quiet

          haxelib run lime rebuild tools --always
          
