name: Build Android
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Libs
        run: |
          haxelib setup ~/haxelib
          haxelib install lime --always
          haxelib install openfl --always
          haxelib install flixel --always
          haxelib install flixel-addons --always
          haxelib install flixel-ui --always
          haxelib install tjson --always
          haxelib install SScript --always
          haxelib install hxvlc --always
          haxelib git hxCodec https://github.com/MAJigsaw77-Ports/hxCodec --always
          haxelib git extension-androidtools https://github.com/Shadow-Droid-Team/extension-androidtools --always
          haxelib git androiddialogs https://github.com/Shadow-Droid-Team/androiddialogs --always
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit --always
          haxelib run lime setup android
          haxelib run lime setup

      - name: Compile
        run: |
          haxelib run lime build android -release
          
