name: Droid Build Force 0.7.1h
on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install Libs
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.1.1 --always
          haxelib install openfl 9.3.3 --always
          haxelib install flixel 5.5.0 --always
          haxelib install flixel-addons --always
          haxelib install flixel-ui --always
          haxelib install tjson --always
          haxelib install SScript --always
          haxelib install hxvlc --always
          
          # SEUS 3 LINKS QUE FUNCIONAM
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec --always
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit --always
          haxelib git extension-androidtools https://github.com/LimeExtensions/extension-androidtools --always
          
          # REMOVENDO O ANDROIDDIALOGS QUE ESTÁ QUEBRADO
          sed -i '/androiddialogs/d' Project.xml

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Configure Lime/Android
        run: |
          # Aqui definimos as rotas que o erro apontou
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_HOME/ndk-bundle
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime setup android -noprompt

      - name: Build APK
        # Forçamos a leitura das variáveis aqui também
        run: |
          export ANDROID_SDK=$ANDROID_HOME
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
          haxelib run lime build android -debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DroidEngine-Debug
          path: export/debug/android/bin/app/build/outputs/apk/debug/*.apk
          
