name: Build_Android
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Instalar Bibliotecas
        run: |
          haxelib setup ~/haxelib
          haxelib install format --always
          haxelib install hxp --always
          haxelib install lime --always
          haxelib install openfl --always
          haxelib install flixel 5.2.2 --always
          haxelib install flixel-addons --always
          haxelib install flixel-ui --always
          haxelib install hscript --always
          haxelib install tjson --always
          haxelib install SScript --always
          haxelib install hxvlc --always
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec --always
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit --always
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools --always
          haxelib run lime rebuild tools --always

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_HOME/ndk-bundle
          haxelib run lime setup android -noprompt
          haxelib run lime build android -debug -clean -D no-android-dialogs -D no-device-lang

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Jogo-Android
          path: export/android/bin/app/build/outputs/apk/debug/*.apk
          
