      - name: Instalar Bibliotecas
        run: |
          haxelib setup ~/haxelib
          
          # 1. Suporte
          haxelib install format --always --quiet
          haxelib install hxp --always --quiet
          
          # 2. O PULO DO GATO: Instalação via Servidor Haxelib (Imune a 404)
          # Se o seu Project.xml pedir "androiddialogs", esse comando resolve:
          haxelib install androiddialogs --always --quiet
          
          # 3. Otimização Lime e OpenFL (Ainda via Git porque estes são estáveis)
          haxelib git lime https://github.com/openfl/lime --always
          haxelib git openfl https://github.com/openfl/openfl --always
          
          # 4. Seus 3 links de confiança
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec --always
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit --always
          haxelib git extension-androidtools https://github.com/LimeExtensions/extension-androidtools --always
          
          # 5. Dependências do motor
          haxelib install flixel 5.5.0 --always --quiet
          haxelib install flixel-addons --always --quiet
          haxelib install flixel-ui --always --quiet
          haxelib install hscript --always --quiet
          haxelib install tjson --always --quiet
          haxelib install SScript --always --quiet
          haxelib install hxvlc --always --quiet

          # 6. Rebuild Final
          haxelib run lime rebuild tools --always
