name: Build Droid Engine Force
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Libs (Ignora se falhar)
        continue-on-error: true
        run: |
          haxelib install lime 8.0.1
          haxelib install openfl 9.2.1
          haxelib install flixel 5.2.2
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install tjson
          haxelib git hxCodec https://github.com/polyaneul/hxCodec
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools

      - name: Configure Android SDK
        continue-on-error: true
        uses: android-actions/setup-android@v2

      - name: Compile APK (Tentativa Forçada)
        id: compile
        continue-on-error: true
        run: haxelib run lime build android -release

      - name: Upload se o APK existir
        uses: actions/upload-artifact@v3
        if: always() # Faz o upload mesmo que a compilação tenha dado erro
        with:
          name: DroidEngine-Resultado
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
