      - name: Install Haxelib (Modo Rápido 0.7.1h)
        run: |
          haxelib setup ~/haxelib
          # Versões compatíveis com 0.7.1h
          haxelib git lime https://github.com/mcagabe19/lime --always
          haxelib git openfl https://github.com/openfl/openfl --always
          haxelib git flixel https://github.com/HaxeFlixel/flixel --always
          haxelib install flixel-addons --always
          haxelib install flixel-ui --always
          haxelib install tjson --always
          haxelib install SScript --always
          haxelib install hxvlc --always
          
          # LINKS ATUALIZADOS (O segredo para não dar erro 404)
          haxelib git extension-androidtools https://github.com/Shadow-Droid-Team/extension-androidtools --always
          haxelib git androiddialogs https://github.com/Shadow-Droid-Team/androiddialogs --always
          haxelib git hxCodec https://github.com/MAJigsaw77-Ports/hxCodec --always
          
          haxelib run lime setup android
          haxelib run lime setup
          
