name: Build Droid Engine Final
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Libs
        run: |
          haxelib install lime 8.0.1
          haxelib install openfl 9.2.1
          haxelib install flixel 5.2.2
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install tjson
          haxelib git hxCodec https://github.com/polyaneul/hxCodec
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools
          haxelib run lime setup flixel
          haxelib run lime setup

      - name: Setup Android
        uses: android-actions/setup-android@v2

      - name: Compile (Force APK)
        # O '|| true' impede que o GitHub pare o processo se houver avisos (warnings)
        run: haxelib run lime build android -release || true

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: APK_Droid_Engine
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
