name: Build Android Port
on:
  push:
    branches: [ main, experimental ]
  pull_request:
    branches: [ main, experimental ]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK/NDK
        uses: android-actions/setup-android@v3
      
      - name: Install Android Components
        run: |
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-33" "build-tools;33.0.0" "ndk;25.2.9519653"
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Install Haxelib (Modo Blindado)
        run: |
          haxelib setup ~/haxelib
          # Instalando as bibliotecas base via ZIP para evitar erro de clone
          haxelib install hxcpp > /dev/null --quiet
          haxelib install lime 8.1.2 --always
          haxelib install openfl 9.3.3 --always
          haxelib install flixel 5.5.0 --always
          haxelib install flixel-addons 3.2.1 --always
          haxelib install flixel-ui --always
          haxelib install tjson --always
          haxelib install SScript --always
          
          # Bibliotecas Git com links corrigidos e sem barra no final
          haxelib git linc_luajit https://github.com/nebulatv/linc_luajit --always
          haxelib git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd --always
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools --always
          
          haxelib run lime setup android
          haxelib run lime setup

      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile APK
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          # Compilando para Android
          haxelib run lime build android -release -D officialBuild

      - name: Publish Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: androidBuild-PsychPort
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
