name: Droid Build Force
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Libs (Turbo Mode)
        run: |
          haxelib setup ~/haxelib
          # Isso baixa o LIME em segundos, permitindo que suas funções compilem
          haxelib git lime https://github.com/haxelime/lime
          haxelib install openfl 9.2.1 --always
          haxelib install flixel 5.2.2 --always
          haxelib install flixel-addons --always
          haxelib install flixel-ui --always
          haxelib install tjson --always
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools
          haxelib run lime setup

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build APK (Compilando suas funções)
        run: haxelib run lime build android -release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: DroidEngine-Com-Minhas-Funcoes
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
